# Generated by Django 4.2.2 on 2023-07-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeConocimiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Area de conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('nro_de_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(null=True)),
                ('salario', models.FloatField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.banco')),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo_vacante', models.CharField(max_length=255)),
                ('descripcion_del_cargo', models.CharField(max_length=255, null=True)),
                ('salario', models.FloatField()),
                ('estado', models.BooleanField()),
                ('area_de_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.areadeconocimiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.empresa')),
            ],
            options={
                'db_table': 'Oferta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.IntegerField()),
                ('rol', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='UTrabajador',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.IntegerField()),
                ('rol', models.SmallIntegerField()),
                ('tipo_de_sangre', models.CharField(max_length=2)),
                ('persona_de_contacto', models.IntegerField()),
                ('numero_de_emergencia', models.IntegerField()),
            ],
            options={
                'db_table': 'U_Trabajador',
            },
        ),
        migrations.CreateModel(
            name='UEmpresa',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.IntegerField()),
                ('rol', models.SmallIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.empresa')),
            ],
            options={
                'db_table': 'U_Empresa',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha_de_pago', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.contrato')),
            ],
            options={
                'db_table': 'Recibo',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.oferta')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.utrabajador')),
            ],
            options={
                'db_table': 'Postulacion',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.utrabajador')),
            ],
            options={
                'db_table': 'Experiencia Laboral',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.oferta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.utrabajador'),
        ),
        migrations.AddField(
            model_name='banco',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.utrabajador'),
        ),
        migrations.CreateModel(
            name='AreaTrabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_de_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.areadeconocimiento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HG_APPS.utrabajador')),
            ],
            options={
                'db_table': 'Area_Trabajador',
            },
        ),
    ]
