# Generated by Django 4.2.2 on 2023-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HG_APPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nro_de_cuenta',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uempresa',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='utrabajador',
            name='numero_de_emergencia',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='utrabajador',
            name='persona_de_contacto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='utrabajador',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
