# Generated by Django 4.2.2 on 2023-07-10 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HG_APPS', '0002_alter_banco_nro_de_cuenta_alter_uempresa_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uempresa',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='uempresa',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='utrabajador',
            name='telefono',
        ),
        migrations.AddField(
            model_name='uempresa',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HG_APPS.usuario'),
        ),
        migrations.AddField(
            model_name='utrabajador',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HG_APPS.usuario'),
        ),
    ]
